version: '2'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=p4SSW0rd
      - MYSQL_DATABASE=calculator
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
  calculator:
    image: cloudconsulting/calculator:0.0.1
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=calculator
      - DATABASE_PORT=3306