version: '2.1'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=p4SSW0rd
      - MYSQL_DATABASE=calculator
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
  calculator:
    image: 334344561596.dkr.ecr.us-east-1.amazonaws.com/calculator
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=calculator
      - DATABASE_PORT=3306