spring:
  mvc:
    view:
      prefix: /views/
      suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/calculator
    username: root
    password: p4SSW0rd
    platform: mysql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
---
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .html
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true
  jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      ddl-auto: none